export CUDA_VISIBLE_DEVICES="3"
python train_combiner.py \
	--exp_name debug_combiner                             \
	--data_path ./combiner_data \
	--lgs 'zh-en'                                        \
	--encoder_only True                                 \
	--emb_dim 1024                                       \
	--n_layers 6                                         \
	--n_heads 8                                          \
	--dropout 0.1                                        \
	--attention_dropout 0.1                              \
	--gelu_activation true                               \
	--batch_size 2 \
	--optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 \
	--epoch_size 128                                  \
	--max_epoch 1                                      \
	--src_bped_words_path ./word_vocab/zh.vocab.bpe \
	--tgt_bped_words_path ./word_vocab/en.vocab.bpe \
	--dict_src_lang zh \
	--dict_tgt_lang en \
	--dict_path /home/data_ti5_d/zhouzh/low-resource-mt/XLM_MASS_preprocessed_data/BLI/zh-en/zh-en.txt.sim \
	--codes_path /home/data_ti5_d/zhouzh/low-resource-mt/XLM_MASS_preprocessed_data/pretrain/cn-split-sen-zh-en-pretrain/codes \
	--combiner_steps "zh,en"
